### ISSUE TITLE
可否加入平方英尺／平方米／坪的對照表

### ISSUE THREAD

**Issue by yorkxin** [ascendbruce/taiwanese-developers-in-singapore#2]
台灣人習慣的房屋單位是坪，但是新加坡組屋網站通常顯示 sqft / sqm。如果可以加入對照表就更方便了。

我的計算是 SQFT / 35.88 = 坪

**Comment by ascendbruce** [comment]
updated: https://github.com/ascendbruce/taiwanese-developers-in-singapore/wiki/%E6%96%B0%E5%8A%A0%E5%9D%A1%E7%A7%9F%E5%B1%8B#%E7%A7%9F%E5%B1%8B%E7%B6%B2

thanks for the feedback

**Comment by yorkxin** [comment]
cool!
