### ISSUE TITLE
國民年金

### ISSUE THREAD

**Issue by yichengwan** [ascendbruce/taiwanese-developers-in-singapore#4]
依照法規，國民年金是每個中華民國國民的權利與義務，也就是說，依法，你必須要交，無論你人在國內還是國外。但是，目前的法規並沒有規範"不交"的罰則，所以當你出國工作後，你的家人(通訊地址)會收到催繳單。看起來很恐怖，但是其實你不繳錢的話，是沒有任何罰則的。另外，有人可能會說，你不繳錢，以後就拿不到國民年金。先不論這個國民年金的龐氏騙局能不能活到我們可以領的那天，假若你回台灣了，年紀也到了想領了，只要補齊以前缺繳金額，就可以一樣領取年金。對，你沒看錯，你不用繳利息，但是政府還是要用國民年金的利率發給你福利年金。這麼好康的事，怎麼可能？就是有可能，不然我們的政府怎麼會財政赤字成這樣，光是老農年金與老人年金就吃死預算了。蔡政府說有可能會修改國民年金缺繳的法規，到時候在更新這個部分。

**Comment by ascendbruce** [comment]
謝謝您補充國民年金的部分 😃
